title: Open Source Systems Engineering
author: Joseph Lyman
email: joseph.e.lyman@utah.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the project website for J. Lyman's capstone Electrical
  Engineering project. The goal of the project is to demonstrate
  GitHub as an open-source platform for Systems Engineering. This
  project serves as a case study for Agile Development Methodology,
  which is particularly well-suited for the volatile nature of GitHub
  projects.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
